bind = SUPER, I, layoutmsg, addmaster
bind = SUPER, D, layoutmsg, removemaster

# User super + return to set current focused to master.
unbind = SUPER, RETURN
bindd = CTRL ALT, T, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
bind = SUPER, RETURN, layoutmsg, swapwithmaster

# Custom screenshot shortcut to always copy to clipboard + save
bind = ALT SHIFT, 4, exec, grim -g "$(slurp)" - | satty -f - --output-filename ~/Pictures/Screenshots/Screenshot_$(date +%Y%m%d_%H%M%S).png --copy-command wl-copy --actions-on-escape="save-to-clipboard,save-to-file,exit" --actions-on-enter="save-to-clipboard,save-to-file,exit" --floating-hack --initial-tool=arrow --annotation-size-factor=0.5

# Window manager on SUPER + E
bindd = SUPER, E, File manager, exec, uwsm-app -- nautilus --new-window

# Close with SUPER + Q
unbind = SUPER, W
bindd = SUPER, Q, Close window, killactive,

# Lock with super + L

unbind = SUPER, L
bindd = SUPER, L, Lock system, exec, omarchy system lock


# Add sound to volume change.
bindel = ,XF86AudioRaiseVolume, exec, omarchy-swayosd-client --output-volume raise && ogg123 -q ~/.local/share/omarchy-supplement-resources/audio-volume-change.oga
bindel = ,XF86AudioLowerVolume, exec, omarchy-swayosd-client --output-volume lower && ogg123 -q ~/.local/share/omarchy-supplement-resources/audio-volume-change.oga


